/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Square.Connect.Model
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BatchRetrieveCatalogObjectsResponse :  IEquatable<BatchRetrieveCatalogObjectsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchRetrieveCatalogObjectsResponse" /> class.
        /// </summary>
        /// <param name="Errors">The set of [Error](#type-error)s encountered..</param>
        /// <param name="Objects">A list of [CatalogObject](#type-catalogobject)s returned..</param>
        /// <param name="RelatedObjects">A list of [CatalogObject](#type-catalogobject)s referenced by the object in the &#x60;objects&#x60; field..</param>
        public BatchRetrieveCatalogObjectsResponse(List<Error> Errors = default(List<Error>), List<CatalogObject> Objects = default(List<CatalogObject>), List<CatalogObject> RelatedObjects = default(List<CatalogObject>))
        {
            this.Errors = Errors;
            this.Objects = Objects;
            this.RelatedObjects = RelatedObjects;
        }
        
        /// <summary>
        /// The set of [Error](#type-error)s encountered.
        /// </summary>
        /// <value>The set of [Error](#type-error)s encountered.</value>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<Error> Errors { get; set; }
        /// <summary>
        /// A list of [CatalogObject](#type-catalogobject)s returned.
        /// </summary>
        /// <value>A list of [CatalogObject](#type-catalogobject)s returned.</value>
        [DataMember(Name="objects", EmitDefaultValue=false)]
        public List<CatalogObject> Objects { get; set; }
        /// <summary>
        /// A list of [CatalogObject](#type-catalogobject)s referenced by the object in the &#x60;objects&#x60; field.
        /// </summary>
        /// <value>A list of [CatalogObject](#type-catalogobject)s referenced by the object in the &#x60;objects&#x60; field.</value>
        [DataMember(Name="related_objects", EmitDefaultValue=false)]
        public List<CatalogObject> RelatedObjects { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchRetrieveCatalogObjectsResponse {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Objects: ").Append(Objects).Append("\n");
            sb.Append("  RelatedObjects: ").Append(RelatedObjects).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BatchRetrieveCatalogObjectsResponse);
        }

        /// <summary>
        /// Returns true if BatchRetrieveCatalogObjectsResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of BatchRetrieveCatalogObjectsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchRetrieveCatalogObjectsResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Errors == other.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(other.Errors)
                ) && 
                (
                    this.Objects == other.Objects ||
                    this.Objects != null &&
                    this.Objects.SequenceEqual(other.Objects)
                ) && 
                (
                    this.RelatedObjects == other.RelatedObjects ||
                    this.RelatedObjects != null &&
                    this.RelatedObjects.SequenceEqual(other.RelatedObjects)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Errors != null)
                    hash = hash * 59 + this.Errors.GetHashCode();
                if (this.Objects != null)
                    hash = hash * 59 + this.Objects.GetHashCode();
                if (this.RelatedObjects != null)
                    hash = hash * 59 + this.RelatedObjects.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
