/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Square.Connect.Model
{
    /// <summary>
    /// Defines the fields that are included in the response body of a request to the [CreateCheckout](#endpoint-createcheckout) endpoint.
    /// </summary>
    [DataContract]
    public partial class CreateCheckoutResponse :  IEquatable<CreateCheckoutResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCheckoutResponse" /> class.
        /// </summary>
        /// <param name="Checkout">The newly created checkout. If the same request was made with the same idempotency_key, this will be the checkout created with the idempotency_key..</param>
        /// <param name="Errors">Any errors that occurred during the request..</param>
        public CreateCheckoutResponse(Checkout Checkout = default(Checkout), List<Error> Errors = default(List<Error>))
        {
            this.Checkout = Checkout;
            this.Errors = Errors;
        }
        
        /// <summary>
        /// The newly created checkout. If the same request was made with the same idempotency_key, this will be the checkout created with the idempotency_key.
        /// </summary>
        /// <value>The newly created checkout. If the same request was made with the same idempotency_key, this will be the checkout created with the idempotency_key.</value>
        [DataMember(Name="checkout", EmitDefaultValue=false)]
        public Checkout Checkout { get; set; }
        /// <summary>
        /// Any errors that occurred during the request.
        /// </summary>
        /// <value>Any errors that occurred during the request.</value>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<Error> Errors { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCheckoutResponse {\n");
            sb.Append("  Checkout: ").Append(Checkout).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateCheckoutResponse);
        }

        /// <summary>
        /// Returns true if CreateCheckoutResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateCheckoutResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCheckoutResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Checkout == other.Checkout ||
                    this.Checkout != null &&
                    this.Checkout.Equals(other.Checkout)
                ) && 
                (
                    this.Errors == other.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(other.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Checkout != null)
                    hash = hash * 59 + this.Checkout.GetHashCode();
                if (this.Errors != null)
                    hash = hash * 59 + this.Errors.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
