/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Square.Connect.Model
{
    /// <summary>
    /// The response to a request for a set of &#x60;BreakTypes&#x60;. Contains the requested &#x60;BreakType&#x60; objects. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors.
    /// </summary>
    [DataContract]
    public partial class ListBreakTypesResponse :  IEquatable<ListBreakTypesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListBreakTypesResponse" /> class.
        /// </summary>
        /// <param name="BreakTypes"> A page of &#x60;BreakType&#x60; results..</param>
        /// <param name="Cursor">Value supplied in the subsequent request to fetch the next next page of Break Type results..</param>
        /// <param name="Errors">Any errors that occurred during the request..</param>
        public ListBreakTypesResponse(List<BreakType> BreakTypes = default(List<BreakType>), string Cursor = default(string), List<Error> Errors = default(List<Error>))
        {
            this.BreakTypes = BreakTypes;
            this.Cursor = Cursor;
            this.Errors = Errors;
        }
        
        /// <summary>
        ///  A page of &#x60;BreakType&#x60; results.
        /// </summary>
        /// <value> A page of &#x60;BreakType&#x60; results.</value>
        [DataMember(Name="break_types", EmitDefaultValue=false)]
        public List<BreakType> BreakTypes { get; set; }
        /// <summary>
        /// Value supplied in the subsequent request to fetch the next next page of Break Type results.
        /// </summary>
        /// <value>Value supplied in the subsequent request to fetch the next next page of Break Type results.</value>
        [DataMember(Name="cursor", EmitDefaultValue=false)]
        public string Cursor { get; set; }
        /// <summary>
        /// Any errors that occurred during the request.
        /// </summary>
        /// <value>Any errors that occurred during the request.</value>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<Error> Errors { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListBreakTypesResponse {\n");
            sb.Append("  BreakTypes: ").Append(BreakTypes).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ListBreakTypesResponse);
        }

        /// <summary>
        /// Returns true if ListBreakTypesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ListBreakTypesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListBreakTypesResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BreakTypes == other.BreakTypes ||
                    this.BreakTypes != null &&
                    this.BreakTypes.SequenceEqual(other.BreakTypes)
                ) && 
                (
                    this.Cursor == other.Cursor ||
                    this.Cursor != null &&
                    this.Cursor.Equals(other.Cursor)
                ) && 
                (
                    this.Errors == other.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(other.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BreakTypes != null)
                    hash = hash * 59 + this.BreakTypes.GetHashCode();
                if (this.Cursor != null)
                    hash = hash * 59 + this.Cursor.GetHashCode();
                if (this.Errors != null)
                    hash = hash * 59 + this.Errors.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
