/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Square.Connect.Model
{
    /// <summary>
    /// A request for a set of &#x60;EmployeeWage&#x60; objects
    /// </summary>
    [DataContract]
    public partial class ListEmployeeWagesRequest :  IEquatable<ListEmployeeWagesRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListEmployeeWagesRequest" /> class.
        /// </summary>
        /// <param name="EmployeeId">Filter wages returned to only those that are associated with the specified employee..</param>
        /// <param name="Limit">Maximum number of Employee Wages to return per page. Can range between 1 and 200. The default is the maximum at 200..</param>
        /// <param name="Cursor">Pointer to the next page of Employee Wage results to fetch..</param>
        public ListEmployeeWagesRequest(string EmployeeId = default(string), int? Limit = default(int?), string Cursor = default(string))
        {
            this.EmployeeId = EmployeeId;
            this.Limit = Limit;
            this.Cursor = Cursor;
        }
        
        /// <summary>
        /// Filter wages returned to only those that are associated with the specified employee.
        /// </summary>
        /// <value>Filter wages returned to only those that are associated with the specified employee.</value>
        [DataMember(Name="employee_id", EmitDefaultValue=false)]
        public string EmployeeId { get; set; }
        /// <summary>
        /// Maximum number of Employee Wages to return per page. Can range between 1 and 200. The default is the maximum at 200.
        /// </summary>
        /// <value>Maximum number of Employee Wages to return per page. Can range between 1 and 200. The default is the maximum at 200.</value>
        [DataMember(Name="limit", EmitDefaultValue=false)]
        public int? Limit { get; set; }
        /// <summary>
        /// Pointer to the next page of Employee Wage results to fetch.
        /// </summary>
        /// <value>Pointer to the next page of Employee Wage results to fetch.</value>
        [DataMember(Name="cursor", EmitDefaultValue=false)]
        public string Cursor { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListEmployeeWagesRequest {\n");
            sb.Append("  EmployeeId: ").Append(EmployeeId).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ListEmployeeWagesRequest);
        }

        /// <summary>
        /// Returns true if ListEmployeeWagesRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ListEmployeeWagesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListEmployeeWagesRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.EmployeeId == other.EmployeeId ||
                    this.EmployeeId != null &&
                    this.EmployeeId.Equals(other.EmployeeId)
                ) && 
                (
                    this.Limit == other.Limit ||
                    this.Limit != null &&
                    this.Limit.Equals(other.Limit)
                ) && 
                (
                    this.Cursor == other.Cursor ||
                    this.Cursor != null &&
                    this.Cursor.Equals(other.Cursor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.EmployeeId != null)
                    hash = hash * 59 + this.EmployeeId.GetHashCode();
                if (this.Limit != null)
                    hash = hash * 59 + this.Limit.GetHashCode();
                if (this.Cursor != null)
                    hash = hash * 59 + this.Cursor.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            // Limit (int?) maximum
            if(this.Limit > (int?)200)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value less than or equal to 200.", new [] { "Limit" });
            }

            // Limit (int?) minimum
            if(this.Limit < (int?)1)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value greater than or equal to 1.", new [] { "Limit" });
            }

            yield break;
        }
    }

}
