/* 
 * Square Connect API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Square.Connect.Model
{
    /// <summary>
    /// Indicates the method used to enter the card's details.
    /// </summary>
    /// <value>Indicates the method used to enter the card's details.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TenderCardDetailsEntryMethod
    {
        
        /// <summary>
        /// Enum SWIPED for "SWIPED"
        /// </summary>
        [EnumMember(Value = "SWIPED")]
        SWIPED,
        
        /// <summary>
        /// Enum KEYED for "KEYED"
        /// </summary>
        [EnumMember(Value = "KEYED")]
        KEYED,
        
        /// <summary>
        /// Enum EMV for "EMV"
        /// </summary>
        [EnumMember(Value = "EMV")]
        EMV,
        
        /// <summary>
        /// Enum ONFILE for "ON_FILE"
        /// </summary>
        [EnumMember(Value = "ON_FILE")]
        ONFILE,
        
        /// <summary>
        /// Enum CONTACTLESS for "CONTACTLESS"
        /// </summary>
        [EnumMember(Value = "CONTACTLESS")]
        CONTACTLESS
    }

}
