/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Square.Connect.Model
{
    /// <summary>
    /// A request to update a &#x60;BreakType&#x60;
    /// </summary>
    [DataContract]
    public partial class UpdateBreakTypeRequest :  IEquatable<UpdateBreakTypeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateBreakTypeRequest" /> class.
        /// </summary>
        /// <param name="BreakType">The updated &#x60;BreakType&#x60;..</param>
        public UpdateBreakTypeRequest(BreakType BreakType = default(BreakType))
        {
            this.BreakType = BreakType;
        }
        
        /// <summary>
        /// The updated &#x60;BreakType&#x60;.
        /// </summary>
        /// <value>The updated &#x60;BreakType&#x60;.</value>
        [DataMember(Name="break_type", EmitDefaultValue=false)]
        public BreakType BreakType { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateBreakTypeRequest {\n");
            sb.Append("  BreakType: ").Append(BreakType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UpdateBreakTypeRequest);
        }

        /// <summary>
        /// Returns true if UpdateBreakTypeRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateBreakTypeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateBreakTypeRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BreakType == other.BreakType ||
                    this.BreakType != null &&
                    this.BreakType.Equals(other.BreakType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BreakType != null)
                    hash = hash * 59 + this.BreakType.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
