/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing BatchRetrieveCatalogObjectsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchRetrieveCatalogObjectsResponseTests
    {
        // TODO uncomment below to declare an instance variable for BatchRetrieveCatalogObjectsResponse
        //private BatchRetrieveCatalogObjectsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchRetrieveCatalogObjectsResponse
            //instance = new BatchRetrieveCatalogObjectsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchRetrieveCatalogObjectsResponse
        /// </summary>
        [Test]
        public void BatchRetrieveCatalogObjectsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchRetrieveCatalogObjectsResponse
            //Assert.IsInstanceOfType<BatchRetrieveCatalogObjectsResponse> (instance, "variable 'instance' is a BatchRetrieveCatalogObjectsResponse");
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Objects'
        /// </summary>
        [Test]
        public void ObjectsTest()
        {
            // TODO unit test for the property 'Objects'
        }
        /// <summary>
        /// Test the property 'RelatedObjects'
        /// </summary>
        [Test]
        public void RelatedObjectsTest()
        {
            // TODO unit test for the property 'RelatedObjects'
        }

    }

}
