/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing BatchChangeInventoryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchChangeInventoryRequestTests
    {
        // TODO uncomment below to declare an instance variable for BatchChangeInventoryRequest
        //private BatchChangeInventoryRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchChangeInventoryRequest
            //instance = new BatchChangeInventoryRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchChangeInventoryRequest
        /// </summary>
        [Test]
        public void BatchChangeInventoryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchChangeInventoryRequest
            //Assert.IsInstanceOfType<BatchChangeInventoryRequest> (instance, "variable 'instance' is a BatchChangeInventoryRequest");
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Test]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }
        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Test]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }
        /// <summary>
        /// Test the property 'IgnoreUnchangedCounts'
        /// </summary>
        [Test]
        public void IgnoreUnchangedCountsTest()
        {
            // TODO unit test for the property 'IgnoreUnchangedCounts'
        }

    }

}
