/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing CashPaymentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CashPaymentDetailsTests
    {
        // TODO uncomment below to declare an instance variable for CashPaymentDetails
        //private CashPaymentDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CashPaymentDetails
            //instance = new CashPaymentDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CashPaymentDetails
        /// </summary>
        [Test]
        public void CashPaymentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CashPaymentDetails
            //Assert.IsInstanceOfType<CashPaymentDetails> (instance, "variable 'instance' is a CashPaymentDetails");
        }

        /// <summary>
        /// Test the property 'BuyerSuppliedMoney'
        /// </summary>
        [Test]
        public void BuyerSuppliedMoneyTest()
        {
            // TODO unit test for the property 'BuyerSuppliedMoney'
        }
        /// <summary>
        /// Test the property 'ChangeBackMoney'
        /// </summary>
        [Test]
        public void ChangeBackMoneyTest()
        {
            // TODO unit test for the property 'ChangeBackMoney'
        }

    }

}
