/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing CatalogQueryFilteredItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CatalogQueryFilteredItemsTests
    {
        // TODO uncomment below to declare an instance variable for CatalogQueryFilteredItems
        //private CatalogQueryFilteredItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CatalogQueryFilteredItems
            //instance = new CatalogQueryFilteredItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CatalogQueryFilteredItems
        /// </summary>
        [Test]
        public void CatalogQueryFilteredItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CatalogQueryFilteredItems
            //Assert.IsInstanceOfType<CatalogQueryFilteredItems> (instance, "variable 'instance' is a CatalogQueryFilteredItems");
        }

        /// <summary>
        /// Test the property 'TextFilter'
        /// </summary>
        [Test]
        public void TextFilterTest()
        {
            // TODO unit test for the property 'TextFilter'
        }
        /// <summary>
        /// Test the property 'SearchVendorCode'
        /// </summary>
        [Test]
        public void SearchVendorCodeTest()
        {
            // TODO unit test for the property 'SearchVendorCode'
        }
        /// <summary>
        /// Test the property 'CategoryIds'
        /// </summary>
        [Test]
        public void CategoryIdsTest()
        {
            // TODO unit test for the property 'CategoryIds'
        }
        /// <summary>
        /// Test the property 'StockLevels'
        /// </summary>
        [Test]
        public void StockLevelsTest()
        {
            // TODO unit test for the property 'StockLevels'
        }
        /// <summary>
        /// Test the property 'EnabledLocationIds'
        /// </summary>
        [Test]
        public void EnabledLocationIdsTest()
        {
            // TODO unit test for the property 'EnabledLocationIds'
        }
        /// <summary>
        /// Test the property 'VendorIds'
        /// </summary>
        [Test]
        public void VendorIdsTest()
        {
            // TODO unit test for the property 'VendorIds'
        }
        /// <summary>
        /// Test the property 'ProductTypes'
        /// </summary>
        [Test]
        public void ProductTypesTest()
        {
            // TODO unit test for the property 'ProductTypes'
        }
        /// <summary>
        /// Test the property 'CustomAttributeFilters'
        /// </summary>
        [Test]
        public void CustomAttributeFiltersTest()
        {
            // TODO unit test for the property 'CustomAttributeFilters'
        }
        /// <summary>
        /// Test the property 'DoesNotExist'
        /// </summary>
        [Test]
        public void DoesNotExistTest()
        {
            // TODO unit test for the property 'DoesNotExist'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Test]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
