/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing CatalogV1Id
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CatalogV1IdTests
    {
        // TODO uncomment below to declare an instance variable for CatalogV1Id
        //private CatalogV1Id instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CatalogV1Id
            //instance = new CatalogV1Id();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CatalogV1Id
        /// </summary>
        [Test]
        public void CatalogV1IdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CatalogV1Id
            //Assert.IsInstanceOfType<CatalogV1Id> (instance, "variable 'instance' is a CatalogV1Id");
        }

        /// <summary>
        /// Test the property '_CatalogV1Id'
        /// </summary>
        [Test]
        public void _CatalogV1IdTest()
        {
            // TODO unit test for the property '_CatalogV1Id'
        }
        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Test]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

    }

}
