/* 
 * Square Connect API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing CreateCheckoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCheckoutRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateCheckoutRequest
        //private CreateCheckoutRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCheckoutRequest
            //instance = new CreateCheckoutRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCheckoutRequest
        /// </summary>
        [Test]
        public void CreateCheckoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCheckoutRequest
            //Assert.IsInstanceOfType<CreateCheckoutRequest> (instance, "variable 'instance' is a CreateCheckoutRequest");
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Test]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'AskForShippingAddress'
        /// </summary>
        [Test]
        public void AskForShippingAddressTest()
        {
            // TODO unit test for the property 'AskForShippingAddress'
        }
        /// <summary>
        /// Test the property 'MerchantSupportEmail'
        /// </summary>
        [Test]
        public void MerchantSupportEmailTest()
        {
            // TODO unit test for the property 'MerchantSupportEmail'
        }
        /// <summary>
        /// Test the property 'PrePopulateBuyerEmail'
        /// </summary>
        [Test]
        public void PrePopulateBuyerEmailTest()
        {
            // TODO unit test for the property 'PrePopulateBuyerEmail'
        }
        /// <summary>
        /// Test the property 'PrePopulateShippingAddress'
        /// </summary>
        [Test]
        public void PrePopulateShippingAddressTest()
        {
            // TODO unit test for the property 'PrePopulateShippingAddress'
        }
        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

    }

}
