/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing CreateShiftRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateShiftRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateShiftRequest
        //private CreateShiftRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateShiftRequest
            //instance = new CreateShiftRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateShiftRequest
        /// </summary>
        [Test]
        public void CreateShiftRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateShiftRequest
            //Assert.IsInstanceOfType<CreateShiftRequest> (instance, "variable 'instance' is a CreateShiftRequest");
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Test]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }
        /// <summary>
        /// Test the property 'Shift'
        /// </summary>
        [Test]
        public void ShiftTest()
        {
            // TODO unit test for the property 'Shift'
        }

    }

}
