/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing ModelBreak
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelBreakTests
    {
        // TODO uncomment below to declare an instance variable for ModelBreak
        //private ModelBreak instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelBreak
            //instance = new ModelBreak();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelBreak
        /// </summary>
        [Test]
        public void ModelBreakInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelBreak
            //Assert.IsInstanceOfType<ModelBreak> (instance, "variable 'instance' is a ModelBreak");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Test]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }
        /// <summary>
        /// Test the property 'EndAt'
        /// </summary>
        [Test]
        public void EndAtTest()
        {
            // TODO unit test for the property 'EndAt'
        }
        /// <summary>
        /// Test the property 'BreakTypeId'
        /// </summary>
        [Test]
        public void BreakTypeIdTest()
        {
            // TODO unit test for the property 'BreakTypeId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExpectedDuration'
        /// </summary>
        [Test]
        public void ExpectedDurationTest()
        {
            // TODO unit test for the property 'ExpectedDuration'
        }
        /// <summary>
        /// Test the property 'IsPaid'
        /// </summary>
        [Test]
        public void IsPaidTest()
        {
            // TODO unit test for the property 'IsPaid'
        }

    }

}
