/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing OrderEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderEntryTests
    {
        // TODO uncomment below to declare an instance variable for OrderEntry
        //private OrderEntry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderEntry
            //instance = new OrderEntry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderEntry
        /// </summary>
        [Test]
        public void OrderEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderEntry
            //Assert.IsInstanceOfType<OrderEntry> (instance, "variable 'instance' is a OrderEntry");
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Test]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

    }

}
