/* 
 * Square Connect API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing RefundStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RefundStatusTests
    {
        // TODO uncomment below to declare an instance variable for RefundStatus
        //private RefundStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RefundStatus
            //instance = new RefundStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RefundStatus
        /// </summary>
        [Test]
        public void RefundStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RefundStatus
            //Assert.IsInstanceOfType<RefundStatus> (instance, "variable 'instance' is a RefundStatus");
        }


    }

}
