/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing UpdateItemModifierListsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateItemModifierListsResponseTests
    {
        // TODO uncomment below to declare an instance variable for UpdateItemModifierListsResponse
        //private UpdateItemModifierListsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateItemModifierListsResponse
            //instance = new UpdateItemModifierListsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateItemModifierListsResponse
        /// </summary>
        [Test]
        public void UpdateItemModifierListsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateItemModifierListsResponse
            //Assert.IsInstanceOfType<UpdateItemModifierListsResponse> (instance, "variable 'instance' is a UpdateItemModifierListsResponse");
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
