/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing V1DeleteCategoryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1DeleteCategoryRequestTests
    {
        // TODO uncomment below to declare an instance variable for V1DeleteCategoryRequest
        //private V1DeleteCategoryRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1DeleteCategoryRequest
            //instance = new V1DeleteCategoryRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1DeleteCategoryRequest
        /// </summary>
        [Test]
        public void V1DeleteCategoryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1DeleteCategoryRequest
            //Assert.IsInstanceOfType<V1DeleteCategoryRequest> (instance, "variable 'instance' is a V1DeleteCategoryRequest");
        }


    }

}
