/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing V1PaymentItemization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1PaymentItemizationTests
    {
        // TODO uncomment below to declare an instance variable for V1PaymentItemization
        //private V1PaymentItemization instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PaymentItemization
            //instance = new V1PaymentItemization();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PaymentItemization
        /// </summary>
        [Test]
        public void V1PaymentItemizationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1PaymentItemization
            //Assert.IsInstanceOfType<V1PaymentItemization> (instance, "variable 'instance' is a V1PaymentItemization");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'ItemizationType'
        /// </summary>
        [Test]
        public void ItemizationTypeTest()
        {
            // TODO unit test for the property 'ItemizationType'
        }
        /// <summary>
        /// Test the property 'ItemDetail'
        /// </summary>
        [Test]
        public void ItemDetailTest()
        {
            // TODO unit test for the property 'ItemDetail'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ItemVariationName'
        /// </summary>
        [Test]
        public void ItemVariationNameTest()
        {
            // TODO unit test for the property 'ItemVariationName'
        }
        /// <summary>
        /// Test the property 'TotalMoney'
        /// </summary>
        [Test]
        public void TotalMoneyTest()
        {
            // TODO unit test for the property 'TotalMoney'
        }
        /// <summary>
        /// Test the property 'SingleQuantityMoney'
        /// </summary>
        [Test]
        public void SingleQuantityMoneyTest()
        {
            // TODO unit test for the property 'SingleQuantityMoney'
        }
        /// <summary>
        /// Test the property 'GrossSalesMoney'
        /// </summary>
        [Test]
        public void GrossSalesMoneyTest()
        {
            // TODO unit test for the property 'GrossSalesMoney'
        }
        /// <summary>
        /// Test the property 'DiscountMoney'
        /// </summary>
        [Test]
        public void DiscountMoneyTest()
        {
            // TODO unit test for the property 'DiscountMoney'
        }
        /// <summary>
        /// Test the property 'NetSalesMoney'
        /// </summary>
        [Test]
        public void NetSalesMoneyTest()
        {
            // TODO unit test for the property 'NetSalesMoney'
        }
        /// <summary>
        /// Test the property 'Taxes'
        /// </summary>
        [Test]
        public void TaxesTest()
        {
            // TODO unit test for the property 'Taxes'
        }
        /// <summary>
        /// Test the property 'Discounts'
        /// </summary>
        [Test]
        public void DiscountsTest()
        {
            // TODO unit test for the property 'Discounts'
        }
        /// <summary>
        /// Test the property 'Modifiers'
        /// </summary>
        [Test]
        public void ModifiersTest()
        {
            // TODO unit test for the property 'Modifiers'
        }

    }

}
