/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing V1UpdateModifierListRequestSelectionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1UpdateModifierListRequestSelectionTypeTests
    {
        // TODO uncomment below to declare an instance variable for V1UpdateModifierListRequestSelectionType
        //private V1UpdateModifierListRequestSelectionType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1UpdateModifierListRequestSelectionType
            //instance = new V1UpdateModifierListRequestSelectionType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1UpdateModifierListRequestSelectionType
        /// </summary>
        [Test]
        public void V1UpdateModifierListRequestSelectionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1UpdateModifierListRequestSelectionType
            //Assert.IsInstanceOfType<V1UpdateModifierListRequestSelectionType> (instance, "variable 'instance' is a V1UpdateModifierListRequestSelectionType");
        }


    }

}
