/* 
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Square.Connect.Api;
using Square.Connect.Model;
using Square.Connect.Client;
using System.Reflection;

namespace Square.Connect.Test
{
    /// <summary>
    ///  Class for testing WorkweekConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkweekConfigTests
    {
        // TODO uncomment below to declare an instance variable for WorkweekConfig
        //private WorkweekConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkweekConfig
            //instance = new WorkweekConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkweekConfig
        /// </summary>
        [Test]
        public void WorkweekConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkweekConfig
            //Assert.IsInstanceOfType<WorkweekConfig> (instance, "variable 'instance' is a WorkweekConfig");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StartOfWeek'
        /// </summary>
        [Test]
        public void StartOfWeekTest()
        {
            // TODO unit test for the property 'StartOfWeek'
        }
        /// <summary>
        /// Test the property 'StartOfDayLocalTime'
        /// </summary>
        [Test]
        public void StartOfDayLocalTimeTest()
        {
            // TODO unit test for the property 'StartOfDayLocalTime'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
